name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        # check out the repository
      - uses: actions/checkout@v3
        # setup node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
        # cache the node_modules folder
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          npm run build:avivator
          touch avivator/dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: avivator/dist
          CLEAN: true
