name: Node.js CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
        # check out the repository
      - uses: actions/checkout@v3
        # setup node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
        # cache the node_modules folder
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Build Avivator and Viv
        run: npm run build && npm run build:avivator

  test-linux:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
        # check out the repository
      - uses: actions/checkout@v3
        # setup node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
        # cache the node_modules folder
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Install dependencies needed for testing with tape
        run: sudo apt-get install xvfb # needed for tape-run

      - name: Test library
        run: xvfb-run --auto-servernum ./test.sh # for tape-run
